[package]
name = "papr-tui"
description = "A keyboard-first terminal workspace for academic papers"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"

[features]
default = ["bundled-sqlite"]
bundled-sqlite = ["papr-core/bundled-sqlite"]

[[bin]]
name = "papr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
arboard.workspace = true
chrono.workspace = true
clap.workspace = true
clap_complete.workspace = true
crossterm.workspace = true
iana-time-zone.workspace = true
papr-core = { path = "../papr-core", version = "0.1.1", default-features = false }
ratatui.workspace = true
ratatui-image.workspace = true
image.workspace = true
reqwest = { workspace = true, features = ["rustls-tls"] }
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
toml.workspace = true
pulldown-cmark.workspace = true
syntect.workspace = true
notify.workspace = true
walkdir.workspace = true

[lints]
workspace = true

[package.metadata.deb]
maintainer = "Afroz Saqlain <sqn3680@gmail.com>, Tanveer <tanveer642003@gmail.com>"
copyright = "2026, Afroz Saqlain <sqn3680@gmail.com>"
extended-description = "A keyboard-first terminal workspace for academic papers."
section = "utility"
priority = "optional"
assets = [
    ["target/release/papr", "usr/bin/papr", "755"],
    ["LICENSE", "usr/share/licenses/papr/LICENSE", "644"],
    ["README.md", "usr/share/doc/papr/README.md", "644"]
]

[package.metadata.generate-rpm]
assets = [
    { source = "../../target/release/papr", dest = "/usr/bin/papr", mode = "755" },
    { source = "LICENSE", dest = "/usr/share/licenses/papr/LICENSE", mode = "644" },
    { source = "README.md", dest = "/usr/share/doc/papr/README.md", mode = "644" }
]
