[package]
name = "papr"
description = "A keyboard-first terminal workspace for academic papers"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
chrono.workspace = true
clap.workspace = true
clap_complete.workspace = true
crossterm.workspace = true
papr-core = { path = "../papr-core", version = "0.1.0" }
ratatui.workspace = true
ratatui-image = { version = "8.1.1", features = ["crossterm", "image-defaults"] }
image = "0.25.10"
reqwest = { workspace = true, features = ["rustls-tls"] }
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
toml.workspace = true
pulldown-cmark = "0.13"
syntect = { version = "5.2", features = ["default-fancy"] }
notify.workspace = true

[lints]
workspace = true
